# Publishes built jars to distribution platforms
name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # any semver tag, e.g. 1.2.3

env:
  # link to the changelog with a format code for the version
  CHANGELOG_LOCATION: "Changelog is available [here](https://github.com/${{github.repository}}/releases/tag/${{github.ref_name}})"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Check for Duplicate Tags
        run: |
          if git rev-parse -q --verify "refs/tags/${{ github.ref }}" >/dev/null; then
            echo "Tag already exists. A version bump is required."
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          add-job-summary: 'never'
          gradle-home-cache-includes: |
            caches
            jdks
            notifications
            wrapper

      - name: Gradle Build
        run: ./gradlew build --build-cache --daemon

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: |
            build/libs/*.jar

  publish_github:
    name: Publish (GitHub)
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to create GitHub releases

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: build/libs

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v3
        with:
          files: "build/libs/*.jar"
          generate_release_notes: true
          fail_on_unmatched_files: true

  publish_curseforge:
    name: Publish (CurseForge)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: build/libs
      - name: Publish to Curseforge
        uses: Kira-NT/mc-publish@v3
        with:
          curseforge-id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}
          changelog: ${{env.CHANGELOG_LOCATION}}
          loaders: |
            forge
          game-versions: |
            [1.12,1.13)
          environment: client | server
          version-type: release